# Generated by Django 5.0.4 on 2024-04-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items')),
                ('type', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('occasion', models.CharField(max_length=100)),
                ('other_details', models.TextField()),
            ],
        ),
    ]
